### PR TITLE
multisig - Fund transfer added new case for scenario 'Internal-tx : Insufficient fee amount'

### PR DESCRIPTION
**Pull request by githubckgoh1439**
Hi, Mostafa & YK

I created test-case for the scenarios of 'Internal-tx : Insufficient fee amount', at LINE - 57 ('sending 9990000000000 cin'). 

After the run-test, I get this Error :

```
Broadcasting internal transaction failed     module=main Result="&{Code:14 Data: Log:{\"codespace\":\"sdk\",\"code\":14,\"message\":\"Insufficient fee amount, need: 1000000000cin\"} Hash:5FB6B032B2100ECBD0A498F326423C838D9E45211CA7BCEA2C02B20B048B56CF}"
```

As I still get the same Error message found in SDK side on last-week, Please comment.

### CODE REVIEW

**Comment by githubckgoh1439** [comment]
Hi, Mostafa & YK

As above the Internal-Tx, 
although I already stated this Tx is not Valid (true, true) for both checkTx & delievryTx,
But while come to multiSig-tx process, because not checking on the InternalTx, so able to continue proceed.  

Do we need the checking?

**Comment by githubckgoh1439** [comment]
Dear all, 

After checked with YK on this issue, this kind of cases need to be checked by using the Block-scanner.

Since it occurred inside a single thread-process which can not be accessible by current-thread, 
the program can not response immediately due to this. 

Example of the single-thread:

```
	go func() {
			// sleep 3 seconds to make sure what ever necessary is completed in previous block.
			time.Sleep(3 * time.Second)
			res, err := rpc.BroadcastTxSync(rpcCtx, bz)
			if err != nil {
				ctx.Logger().Error("Panic on broadcasting internal transaction", "Error", err)
				panic(err)
			}

			if res.Code != 0 {
				ctx.Logger().Error("Broadcasting internal transaction failed", "Result", res)

			}
		}()

```

This kind of tx will not be broadcasted and always be there. 

Please be aware on this kind of cases.

**Comment by yenkhoon** [comment]
no, i mean the users gotto check with scanner. why is there so many merge request?

**Comment by yenkhoon** [comment]
ok i can see u added plenty of test cases thank you. I will approve and merge them.

**Pull request merged**
