### PR TITLE
Add a query interface for fee collector of Nonfungible Token

### PR DESCRIPTION
**Pull request by PandaTea**
There is a fee to be paid to feeCollector when creating a new NFT token.
But no cli-command interface for querying feeCollector is provided to users.

I've added a corresponding interface to make it easier to query feeCollector.

### CODE REVIEW

**Comment by b00f** [comment]
Thanks for your PR.

Could you please send another PR to **develop** branch.  We usually update master branch whenever we have a stable release.
It will be helpful if you can move your changes into develop branch. So you will have the latest code.

Anyways, I have checked your code. It's really good and thank again for making our blockchain better.

**Comment by PandaTea** [comment]
> Thanks for your PR.
> 
> Could you please send another PR to **develop** branch. We usually update master branch whenever we have a stable release.
> It will be helpful if you can move your changes into [develop](https://github.com/maxonrow/maxonrow-go/commits/develop) branch. So you will have the latest code.
> 
> Anyways, I have checked your code. It's really good and thank again for making our blockchain better.

okay thank u , i love u

**Comment by PandaTea** [comment]
I will move my changes into develop branch.I'm sorry for the inconvenience.

**Comment by PandaTea** [comment]
I will move my changes into develop branch.I'm sorry for the inconvenience.

**Pull request closed without merging**
